server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: ${CDC_IMAGE_DB_URL}
    username: ${CDC_IMAGE_DB_USER}
    password: ${CDC_IMAGE_DB_PASSWORD}
    hikari:
      data-source-properties:
        ssl: true
        sslmode: verify-ca
        sslrootcert: ${CDC_IMAGE_DB_SSL_ROOT_CERT_PATH}
        sslcert: ${CDC_IMAGE_DB_SSL_CLIENT_CERT_PATH}
        sslkey: ${CDC_IMAGE_DB_SSL_CLIENT_KEY_PATH}
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: ${FLYWAY_BASELINE_ON_MIGRATE:false}
    baseline-version: ${FLYWAY_BASELINE_VERSION:1}
  cloud:
    gcp:
      credentials:
        location: ${CLOUD_GCP_CRED_PATH}

jwt:
  secret: ${JWT_SECRET}
  access-token:
    expiration-min: ${JWT_ACCESS_TOKEN_EXPIRATION_MIN}
  refresh-token:
    expiration-min: ${JWT_REFRESH_TOKEN_EXPIRATION_MIN}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  show-actuator: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/com/hoquangnam45/cdc/image/app/auth/repository/*.xml
