server:
  port: 8083

spring:
  application:
    name: image-event-handler
  datasource:
    url: ${CDC_IMAGE_DB_URL}
    username: ${CDC_IMAGE_DB_USER}
    password: ${CDC_IMAGE_DB_PASSWORD}
    hikari:
      data-source-properties:
        ssl: true
        sslmode: verify-ca
        sslrootcert: ${CDC_IMAGE_DB_SSL_ROOT_CERT_PATH}
        sslcert: ${CDC_IMAGE_DB_SSL_CLIENT_CERT_PATH}
        sslkey: ${CDC_IMAGE_DB_SSL_CLIENT_KEY_PATH}
  flyway:
    enabled: false # This service does not manage migrations
  cloud:
    gcp:
      pubsub:
        subscriber:
          executor-threads: ${APP_PUBSUB_EXECUTOR_THREAD_NUM:4}
          parallel-pull-count: ${APP_PUBSUB_PARALLEL_PULL_COUNT:1}

jwt:
  secret: ${JWT_SECRET}

management:
  endpoint:
    health:
      probes:
        enabled: true

app:
  subscription:
    upload-image: ${APP_SUBSCRIPTION_UPLOAD_IMAGE}

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/com/hoquangnam4s/cdc/image/app/event/repository/*.xml
