spring:
  application:
    name: app
  datasource:
    url: ${CDC_IMAGE_DB_URL}
    username: ${CDC_IMAGE_DB_USER}
    password: ${CDC_IMAGE_DB_PASSWORD}
    hikari:
      data-source-properties:
        ssl: true
        sslmode: verify-ca
        sslrootcert: ${CDC_IMAGE_DB_SSL_ROOT_CERT_PATH}
        sslcert: ${CDC_IMAGE_DB_SSL_CLIENT_CERT_PATH}
        sslkey: ${CDC_IMAGE_DB_SSL_CLIENT_KEY_PATH}
  flyway:
    baseline-on-migrate: ${FLYWAY_BASELINE_ON_MIGRATE}
    baseline-version: ${FLYWAY_BASELINE_VERSION}
  cloud:
    gcp:
      pubsub:
        subscriber:
          executor-threads: ${APP_PUBSUB_EXECUTOR_THREAD_NUM}
          parallel-pull-count: ${APP_PUBSUB_PARALLEL_PULL_COUNT}
      credentials:
        location: ${CLOUD_GCP_CRED_PATH}

gcp:
  storage:
    bucket-name: ${GCP_STORAGE_BUCKET_NAME}
    presigned-url:
      duration-minute: ${GCP_STORAGE_PRESIGNED_URL_DURATION_MINUTE}

jwt:
  secret: ${JWT_SECRET}
  access-token:
    expiration-min: ${JWT_ACCESS_TOKEN_EXPIRATION_MIN}
  refresh-token:
    expiration-min: ${JWT_REFRESH_TOKEN_EXPIRATION_MIN}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  show-actuator: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true

app:
  subscription:
    upload-image: ${APP_SUBSCRIPTION_UPLOAD_IMAGE}