server:
  port: 8082

spring:
  application:
    name: image-service
  datasource:
    url: ${CDC_IMAGE_DB_URL}
    username: ${CDC_IMAGE_DB_USER}
    password: ${CDC_IMAGE_DB_PASSWORD}
    hikari:
      data-source-properties:
        ssl: true
        sslmode: verify-ca
        sslrootcert: ${CDC_IMAGE_DB_SSL_ROOT_CERT_PATH}
        sslcert: ${CDC_IMAGE_DB_SSL_CLIENT_CERT_PATH}
        sslkey: ${CDC_IMAGE_DB_SSL_CLIENT_KEY_PATH}
  flyway:
    enabled: false # This service does not manage migrations

gcp:
  storage:
    bucket-name: ${GCP_STORAGE_BUCKET_NAME}
    presigned-url:
      duration-minute: ${GCP_STORAGE_PRESIGNED_URL_DURATION_MINUTE}

jwt:
  secret: ${JWT_SECRET} # Needed to validate incoming tokens

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  show-actuator: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/com/hoquangnam4s/cdc/image/app/image/repository/*.xml
