name: Build and Push Services

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-shared:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 21 and Cache Maven Packages
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - id: 'auth'
        name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      # Deploy the parent and common modules in a single command, skipping the now-redundant tests
      - name: Deploy Parent POM and Common Module
        run: ./mvnw -pl .,common clean deploy -DskipTests

  # Job 2: Build all the service images in parallel.
  build-services:
    # This job will only start after the 'build-and-deploy-shared' job succeeds.
    needs: build-and-deploy-shared
    runs-on: ubuntu-latest
    # Use a matrix strategy to run a separate build for each service simultaneously.
    strategy:
      matrix:
        service: [auth-service, image-service, image-event-handler]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 21 and Cache Maven Packages
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - id: 'auth'
        name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Build and Push ${{ matrix.service }}
        run: |
          ./mvnw -pl ${{ matrix.service }} compile com.google.cloud.tools:jib-maven-plugin:3.4.3:build \
            -DskipTests \
            -Djib.to.image=asia-southeast1-docker.pkg.dev/cdc-image-service/cdc-image/${{ matrix.service }}:latest