# .github/workflows/build-and-deploy.yml

name: Build, Push, and Deploy Services

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: cdc-image-service
  REGION: asia-southeast1
  GAR_LOCATION: asia-southeast1-docker.pkg.dev
  REPOSITORY: cdc-image

jobs:
  build-shared-libs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Build and Install Parent and Common Modules
        run: ./mvnw install -DskipTests -U

  build-and-push-services:
    needs: build-shared-libs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth-service, image-service, image-event-handler]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Build and Push ${{ matrix.service }}
        run: |
          ./mvnw -pl ${{ matrix.service }} compile com.google.cloud.tools:jib-maven-plugin:3.4.3:build \
            -DskipTests \
            -Djib.to.image=${{ env.GAR_LOCATION }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ matrix.service }}:${{ github.sha }}

  deploy-auth-service:
    needs: build-and-push-services
    runs-on: ubuntu-latest
    outputs:
      auth_service_url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
      - name: Deploy auth-service and get URL
        id: deploy
        run: |
          gcloud run deploy auth-service \
            --image=${{ env.GAR_LOCATION }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/auth-service:${{ github.sha }} \
            --platform=managed \
            --region=${{ env.REGION }} \
            --project=${{ env.PROJECT_ID }} \
            --allow-unauthenticated \
            --port=8081 \
            --network=cdc-image-vpc-1 \
            --subnet=cloud-run-subnet \
            --vpc-egress=private-ranges-only \
            --startup-probe=httpGet,path=/actuator/health/readiness,port=8081 \
            --liveness-probe=httpGet,path=/actuator/health/liveness,port=8081 \
            --cpu=1 --memory=1Gi \
            --min-instances=1 --max-instances=10 \
            --timeout=300s \
            --service-account=cdc-image-api@cdc-image-service.iam.gserviceaccount.com \
            --update-secrets="/tmp/ssl/certs/ca/ca.pem=db-root-cert:latest,/tmp/ssl/certs/client-cert/client-cert.pem=db-client-cert:latest,/tmp/ssl/certs/client-key/client-key.pem=db-client-key:latest,CDC_IMAGE_DB_URL=db-url:latest,JWT_SECRET=jwt-secret:latest,CDC_IMAGE_DB_USER=db-user:latest,CDC_IMAGE_DB_PASSWORD=db-password:latest" \
            --set-env-vars="CDC_IMAGE_DB_SSL_ROOT_CERT_PATH=/tmp/ssl/certs/ca/ca.pem,CDC_IMAGE_DB_SSL_CLIENT_CERT_PATH=/tmp/ssl/certs/client-cert/client-cert.pem,CDC_IMAGE_DB_SSL_CLIENT_KEY_PATH=/tmp/ssl/certs/client-key/client-key.pem,JWT_ACCESS_TOKEN_EXPIRATION_MIN=30,JWT_REFRESH_TOKEN_EXPIRATION_MIN=10080"
          
          AUTH_URL=$(gcloud run services describe auth-service --platform=managed --region=${{ env.REGION }} --format='value(status.url)')
          echo "url=$AUTH_URL" >> $GITHUB_OUTPUT

  deploy-image-service:
    needs: deploy-auth-service
    runs-on: ubuntu-latest
    outputs:
      image_service_url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
      - name: Deploy image-service and get URL
        id: deploy
        run: |
          gcloud run deploy image-service \
            --image=${{ env.GAR_LOCATION }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/image-service:${{ github.sha }} \
            --platform=managed \
            --region=${{ env.REGION }} \
            --project=${{ env.PROJECT_ID }} \
            --allow-unauthenticated \
            --port=8082 \
            --network=cdc-image-vpc-1 \
            --subnet=cloud-run-subnet \
            --vpc-egress=private-ranges-only \
            --startup-probe=httpGet,path=/actuator/health/readiness,port=8082 \
            --liveness-probe=httpGet,path=/actuator/health/liveness,port=8082 \
            --cpu=1 --memory=1Gi \
            --min-instances=1 --max-instances=5 \
            --timeout=300s \
            --service-account=cdc-image-api@cdc-image-service.iam.gserviceaccount.com \
            --update-secrets="/tmp/ssl/certs/ca/ca.pem=db-root-cert:latest,/tmp/ssl/certs/client-cert/client-cert.pem=db-client-cert:latest,/tmp/ssl/certs/client-key/client-key.pem=db-client-key:latest,CDC_IMAGE_DB_URL=db-url:latest,JWT_SECRET=jwt-secret:latest,CDC_IMAGE_DB_USER=db-user:latest,CDC_IMAGE_DB_PASSWORD=db-password:latest" \
            --set-env-vars="CDC_IMAGE_DB_SSL_ROOT_CERT_PATH=/tmp/ssl/certs/ca/ca.pem,CDC_IMAGE_DB_SSL_CLIENT_CERT_PATH=/tmp/ssl/certs/client-cert/client-cert.pem,CDC_IMAGE_DB_SSL_CLIENT_KEY_PATH=/tmp/ssl/certs/client-key/client-key.pem,GCP_STORAGE_BUCKET_NAME=cdc-image-bucket,GCP_STORAGE_PRESIGNED_URL_DURATION_MINUTE=15"

          IMAGE_URL=$(gcloud run services describe image-service --platform=managed --region=${{ env.REGION }} --format='value(status.url)')
          echo "url=$IMAGE_URL" >> $GITHUB_OUTPUT

  deploy-image-event-handler:
    needs: deploy-auth-service
    runs-on: ubuntu-latest
    outputs:
      job_name: "image-event-handler-job"
    steps:
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
      - name: Deploy image-event-handler as a Cloud Run Job
        run: |
          gcloud run jobs deploy image-event-handler-job \
            --image=${{ env.GAR_LOCATION }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/image-event-handler:${{ github.sha }} \
            --region=${{ env.REGION }} \
            --project=${{ env.PROJECT_ID }} \
            --cpu=1 --memory=1Gi \
            --min-instances=1 --max-instances=20 \
            --task-timeout=300s \
            --service-account=cdc-image-api@cdc-image-service.iam.gserviceaccount.com \
            --update-secrets="/tmp/ssl/certs/ca/ca.pem=db-root-cert:latest,/tmp/ssl/certs/client-cert/client-cert.pem=db-client-cert:latest,/tmp/ssl/certs/client-key/client-key.pem=db-client-key:latest,CDC_IMAGE_DB_URL=db-url:latest,JWT_SECRET=jwt-secret:latest,CDC_IMAGE_DB_USER=db-user:latest,CDC_IMAGE_DB_PASSWORD=db-password:latest" \
            --set-env-vars="CDC_IMAGE_DB_SSL_ROOT_CERT_PATH=/tmp/ssl/certs/ca/ca.pem,CDC_IMAGE_DB_SSL_CLIENT_CERT_PATH=/tmp/ssl/certs/client-cert/client-cert.pem,CDC_IMAGE_DB_SSL_CLIENT_KEY_PATH=/tmp/ssl/certs/client-key/client-key.pem,APP_SUBSCRIPTION_UPLOAD_IMAGE=projects/cdc-image-service/subscriptions/cdc-image-uploaded-image-subscription"

  deployment-summary:
    needs: [deploy-auth-service, deploy-image-service, deploy-image-event-handler]
    runs-on: ubuntu-latest
    steps:
      - name: Deployment Summary
        run: |
          echo "🚀 Deployment Summary:"
          echo "✅ Auth Service: ${{ needs.deploy-auth-service.outputs.auth_service_url }}"
          echo "✅ Image Service: ${{ needs.deploy-image-service.outputs.image_service_url }}"
          echo "✅ Image Event Handler Job: ${{ needs.deploy-image-event-handler.outputs.job_name }}"
          echo ""
          echo "All services deployed successfully in the correct order!"
