name: Deploy to Cloud Run using Jib

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Build and Push Docker Image with Jib
        run: |
          ./mvnw compile com.google.cloud.tools:jib-maven-plugin:3.4.3:build \
            -Djib.to.image=asia-southeast1-docker.pkg.dev/cdc-image-service/cdc-image/cdc-image-service:latest

      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy cdc-image-service \
            --image asia-southeast1-docker.pkg.dev/cdc-image-service/cdc-image/cdc-image-service:latest \
            --region asia-southeast1 \
            --platform managed \
            --allow-unauthenticated
