name: Build and Push Services

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Build and Push auth-service
        run: |
          ./mvnw -pl auth-service compile com.google.cloud.tools:jib-maven-plugin:3.4.3:build \
            -Djib.to.image=asia-southeast1-docker.pkg.dev/cdc-image-service/cdc-image/auth-service:latest

      - name: Build and Push image-service
        run: |
          ./mvnw -pl image-service compile com.google.cloud.tools:jib-maven-plugin:3.4.3:build \
            -Djib.to.image=asia-southeast1-docker.pkg.dev/cdc-image-service/cdc-image/image-service:latest

      - name: Build and Push image-event-handler
        run: |
          ./mvnw -pl image-event-handler compile com.google.cloud.tools:jib-maven-plugin:3.4.3:build \
            -Djib.to.image=asia-southeast1-docker.pkg.dev/cdc-image-service/cdc-image/image-event-handler:latest